name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cleaning Project
        run: mvn clean

      - name: Validating Project
        run: mvn validate

      - name: Testing Project
        run: mvn test

      - name: Compiling Project
        run: mvn compile

      - name: Building Artifact
        run: mvn package
